### ISSUE TITLE
跳到最后验证的时候，显示localhost 拒绝了我们的连接请求。

### ISSUE THREAD

**Issue by qinef** [porjo/youtubeuploader#142]
在弹出“想要访问您的 Google 帐号
选择可访问哪些服务“
都打对钩后，就弹出
无法访问此网站localhost 拒绝了我们的连接请求，我看显示器地址栏里也是显示“http://localhost:8080/oauth2callback?state=st1670857002323783305&code=4/0Afge 。。。。”等一串字符，请教是何原因。

**Comment by qinef** [comment]
when it shows which services you can access to your Google account,i  ticking all the boxes, it will pop up
This site cannot be reached http://localhost:8080/oauth2callback?state=st1670857002323783305&code=4/0Afge.... ,what's wrong?

**Comment by porjo** [comment]
There appears to be two errors:
1. cannot connect to http://localhost:8080
1. executable file not found (youtubeuploader cannot launch the web browser)

Is youtubeuploader running on the same host as the web browser? (it must run on the same host as the web browser in order to generate the `request.token` file).

**Comment by qinef** [comment]
i have done "apt install xdg-open",but  it does't work also. it shows "xdg-open: no method available for opening '"

**Comment by porjo** [comment]
`xdg-open` is part of the xdg-utils package on Ubuntu (I guess that is what you are using?)

You haven't answered my previous question - is youtubeuploader running on the same host as the web browser?

**Comment by qinef** [comment]
i guess web-browser don't support,i have install serveral web browser，when i use lynx ,login to google, it shows you vps dont't support javescript.
youtubeupload runing on the same host as the brower..

**Comment by porjo** [comment]
You need a modern GUI web browser in order to generate the token file for youtubeuploader. You may be able to get that working on VPS but it will be difficult. It will be much easier to generate the token file on your local machine using Chrome or Firefox. If your local machine runs Microsoft Windows then you can use the Windows version of youtubeuploader to generate the `request.token` file . Then copy the token file to the VPS and use it there with the Linux version of youtubeuploader.

**Comment by qinef** [comment]
yes, i have use Microsoft Windows,and it works ,when i open http://localhost:8080/oauth2callback?state=st1671598235044000100&code=4/0AWgavdeqSF8egh17HeOT6_omQDli2jeiXOs_W83fRIWGGRq_v5.....

it shows```
 Received code: 4/0AWgavdeKJYi2KVTrFEMh4-A9WrTz4YbqGdY-Vw8R-hVgvwcsawlXMeT0Zd7KiHyHL7vhfA
You can now safely close this browser window.
```
but token file don't show on the directory of youtubeuploader ,and on the cmd  shows `Your browser has been opened to an authorization URL.  This program will resume
once authorization has been provided.
2022/12/21 12:53:28 Error building OAuth client: Post "https://oauth2.googleapis
.com/token": proxyconnect tcp: dial tcp 127.0.0.1:7777: connectex: No connection
 could be made because the target machine actively refused it.`

**Comment by porjo** [comment]
The message 'proxyconnect tcp: dial tcp 127.0.0.1:7777:' indicates that it is attempting to use a proxy server and it is failing to connect. You need to fix that problem by either removing the proxy configuration if it is not required, or working out why it cannot connect to the proxy.

**Comment by qinef** [comment]
i change another computer to try，and get the request.token, i have upload the reques.token to vsp by winscp,and it works，thanks very much。
