### ISSUE TITLE
How can upload a lot/multiple/folder of videos

### ISSUE THREAD

**Issue by xkpx64** [porjo/youtubeuploader#60]
I got folder full of videos and they got utf-8 names can i upload the whole folder and how ?
I have 1600 videos can't do them one by one, is it possible to upload all .mp4

**Comment by Jaom** [comment]
Technically you can run a script with a loop which sends videos one by one
and eventually sends all. That's what I do.

However you'll hit upload API quota long before 1600 videos. Even earlier
you'll not well documented limit of 100 videos per 24 hours which will
replenish for another 24 hours.

You'd need a script and implement some "waiting" for it to work

**Comment by xkpx64** [comment]
That will be fine i will leave the script for 16 days if needed.
Is this can be done in windows somehow?

**Comment by Jaom** [comment]
1. Batch does not have "wait". I believe the workaround is to make a ping request to non existing IP address with timeout of your preference. Please don't ask me how I got to know that. :-)
2. `-headlessAuth` needs to be run only once (the first time), then you just run `youtubeuploader -filename output.mkv -metaJSON $metaPath -secrets $secretsPath` (everything starting with $ is a variable with the path to the file)
My internal documentation says:
`#How to acquire request.token?
Go for the -headlessAuth option as documented in https://github.com/porjo/youtubeuploader .
It's best to run it once with 'touch fake.mp4' file:
touch fake.mp4 && yt -headlessAuth -filename fake.mp4
There will be an error that the file was bad (this is ok, it was fake). Now you should have request.token in place.`
3. Perhaps you don't need to upload 1600 videos at all. I personally start with around 2500 videos, then i merge them down (in my case this actually it increases the usability). Perhaps you want to merge yours too? This will allow you to limit yourself to the API quota rather than API & 100 videos / 24 limit. If you want to merge videos without re-encoding you can use ffmpeg for that: `ffmpeg -y -f concat -i "_fileList.txt" -codec copy output.mkv`. In my case i run a loop which: merges, sends the merged file and finally removes the merged file.

**Comment by xkpx64** [comment]
They are really 574 episodes but spitted in two or three parts. I will follow that suggestion to combine them to upload faster. Thanks for other tips  But still i dont understand how to setup 99 videos for the day is it something like **for(new i = 99; i < sizeof szStarts; i++)**

**Comment by jorisrobijn** [comment]
You could make multiple directories and manually divide the episode parts into these directories, such that each dir contains less than 100 items. Then for each dir perform the command line above, one dir per day. I like to add in a batch file after the activity that might fail: 
IF ERRORLEVEL 1 PAUSE
otherwise you never find out if it was all ok.

**Comment by xkpx64** [comment]
jorisrobijn that's simple and kinda good and will work thanks
